Support UIDefinition.TextBox.constraints.validations
Azure/arm-ttk pull request #209
Opened 2020-10-09 06:46 UTC by galiacheng

For issue: https://github.com/Azure/arm-ttk/issues/208.

modified: arm-ttk/testcases/CreateUIDefinition/Textboxes-Are-Well-Formed.test.ps1
Support constraints.validations schema.

Testcase:
1. textbox without regex, throw error message: `Textbox $($textbox.Name) is missing constraints.regex or regex property in constraints.validations items`
2. textbox with constraints.regex, test length constraint
3. textbox with constraints.validations[i].regex, test length constraint
4. text validation message.

2020-10-09 20:45 UTC, bmoore-msft requested changes
One comment inline - also, can you add test cases for the new errorIds?

2020-10-09 20:45 UTC, bmoore-msft commented on arm-ttk/testcases/CreateUIDefinition/Textboxes-Are-Well-Formed.test.ps1
> +                Write-Error "Textbox $($textbox.Name) is missing validation message in constraints.validations items" -TargetObject $textbox #error.
Can you add unique error ids for the write-errors - we're trying to close those gaps...

2020-10-10 04:36 UTC, galiacheng commented
Hello @bmoore-msft I created a test case for validations message, please have a look.
new file:   Validations-Must-Have-Message.test.ps1
New error id for validations message.

modified:   Textboxes-Are-Well-Formed.test.ps1
Add error id to error output.

2020-10-12 18:15 UTC, bmoore-msft requested changes

2020-10-12 18:15 UTC, bmoore-msft commented on unit-tests/Textboxes-Are-Well-Formed/Fail/Textboxes-With-Invalid-Regex/createUiDefinition.json
> +                "constraints": {
need to split this up into 1 failure per file - otherwise we don't have a way to know that each one is failing.

2020-10-13 01:14 UTC, galiacheng commented on unit-tests/Textboxes-Are-Well-Formed/Fail/Textboxes-With-Invalid-Regex/createUiDefinition.json
> +                "constraints": {
Done, thank you Brain. Actually, I have different validation for different cases, we can identify from the error message.

2020-10-15 01:21 UTC, galiacheng commented
Hello @bmoore-msft I have split the test cases for invalid regex, please have a look.

2020-10-15 16:06 UTC, bmoore-msft commented
thx

2020-10-15 16:06 UTC, merged