RegEx improvements
Azure/arm-ttk pull request #224
Opened 2020-10-23 19:04 UTC by StartAutomating

Structuring Regular Expressions used within arm-ttk

2020-10-23 19:48 UTC, bmoore-msft commented
Let's expand on the docs and make them more scenario focused - so when would I use one approach vs. the other and show an example of consuming in a test...

2020-11-05 21:11 UTC, StartAutomating commented
We would like some samples of simple patterns / generators inline with /Regex/README.md

2020-11-05 21:48 UTC, bmoore-msft requested changes
Remember to pull first since we made a couple changes during the review

2020-11-05 21:48 UTC, bmoore-msft commented on arm-ttk/Regex/README.md
> +
Let's add an inline example for the content of the txt file in a code block

2020-11-05 21:48 UTC, bmoore-msft commented on arm-ttk/Regex/README.md
> +For instance, using the pattern ARM_Expression, we can find all expressions within the text of a template:
add a step to talk about the hierarchy and how the name is derived, i.e. where does "ARM_Expression" come from

2020-11-05 21:48 UTC, bmoore-msft commented on arm-ttk/Regex/README.md
> +$templateText | & ${?<ARM_Expression>}
add - this will find all the "matches" for the expression in templateText

2020-11-05 21:48 UTC, bmoore-msft commented on arm-ttk/Regex/README.md
> +
same as above lets put the the code inline

And we can also use a simpler example (doesn't have to be real) to highlight the use of a parameter to make the regex more flexible, e.g. whitespace+param+whitespace

2020-11-05 21:48 UTC, bmoore-msft commented on arm-ttk/Regex/README.md
> +Generators need not require parameters.  To find all parameters referenced throughout the template, use:
you could use a generator to find all resources of a given type and return properties for that resource

2020-11-05 21:48 UTC, bmoore-msft commented on arm-ttk/Regex/ARM/Expression.regex.txt
> +\s{0,}                                                     # optional whitespace
can  we add some more detail up top about the depth and balancing groups piece (i.e. why is it relevant to the scenario)

2020-11-05 21:48 UTC, bmoore-msft commented on arm-ttk/Regex/ARM/List_Function.regex.txt
> +﻿(?>        # we don't want to flag a UDF that might be called "myListOfIps" so we need to check the char preceeding list*()
Or's should be more explicit in the comments

2020-11-05 21:48 UTC, bmoore-msft commented on arm-ttk/Writing_TTK_Tests.md
> +~~~
Add a section or another file for how to supply unit tests

2020-11-12 21:37 UTC, StartAutomating commented on arm-ttk/Regex/README.md
> +
Example / "Writing Generator" section added

2020-11-12 21:37 UTC, StartAutomating commented on arm-ttk/Regex/README.md
> +Generators need not require parameters.  To find all parameters referenced throughout the template, use:
We have determined we want a simpler example, using ARM_Parameter.

2020-11-12 21:39 UTC, StartAutomating commented
Upon discussion, we would also like to rename the following expressions:  ARM_Parameter -> ARM_Template_Parameter and ARM_Variable - > ARM_Template_Variable.

Any future expression whose name would be easily confused without clarifying should be named ARM_Template_*

2020-11-20 21:20 UTC, bmoore-msft commented on arm-ttk/Regex/ARM/List_Function.regex.txt
> +list\w{1,}            # which will be list followed by any number of word characters
should we just do this with the TLE generator?

2020-12-03 21:25 UTC, merged