Added tests for DeploymentParameters
Azure/arm-ttk pull request #237
Opened 2020-11-24 15:00 UTC by bobbyangers

DeploymentParameters-ContentVersion-Must-Exist
DeploymentParameters-Parameters-Property-Must-Exist
DeploymentParameters-Parameters-Property-Must-Have-Value

2020-11-24 16:51 UTC, bmoore-msft requested changes
One thing we should pause on this is that the param file doesn't have to have this schema... it can be just the body of the parameters property or it can be the full schema.  Both are valid for ARM to consume.  I assume in that case we'd want to skip all the tests?  or we need to modify how we identify the files and run the tests...

We should doc that case specifically.

2020-11-24 16:51 UTC, bmoore-msft commented on unit-tests/DeploymentParameters-ContentVersion-Must-Exist/Fail/BadFormat.parameters.should.be.txt
> +﻿ContentVersion.Bad.Format
the txt file is only needed if you want to refer to a file that's shared with other tests - so you should be able to remove all the txt files if that holds true for each of them...

2020-11-24 16:51 UTC, bmoore-msft commented on unit-tests/DeploymentParameters-ContentVersion-Must-Exist/Pass/2019-04-01.parameters.json
> +    "contentVersion": "1.0.0.0"
can we vary this a bit to test the regex some (though if we change it to match the schema probably less interesting)

2020-11-24 16:51 UTC, bmoore-msft commented on unit-tests/DeploymentParameters-Parameters-Property-Must-Exist/Fail/NotExist.parameters.should.be.ps1
> +﻿param(
do we need this file (in the unit test folder)?  Not sure what it does...

2020-11-24 16:51 UTC, bmoore-msft commented on unit-tests/DeploymentParameters-Parameters-Property-Must-Exist/Pass/HasParameters.parameters.json
> +    "parameters": {}
add contentVersion to this and you can reuse the file in other tests

2020-11-24 16:51 UTC, bmoore-msft commented on arm-ttk/testcases/deploymentParameters/DeploymentParameters-Parameters-Property-Must-Have-Value.test.ps1
> +    Ensures that all parameters have a property 'value'
this needs to account for reference parameters...

https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/key-vault-parameter?tabs=azure-cli#reference-secrets-with-static-id

Probably just a simple "or" case...

2020-11-24 16:51 UTC, bmoore-msft commented on unit-tests/DeploymentParameters-Parameters-Property-Must-Have-Value/Pass/HasValid.parameters.json
> +            "value" : "some data"
should add other param types here too:
- object, array, bool, int
- reference params

Since they are all passing you could put them into the same file

2020-11-24 16:51 UTC, bmoore-msft commented on unit-tests/DeploymentParameters-Schema-Is-Correct/Fail/BadSchema.parameters.should.be.ps1
> +﻿param(
as above, not sure what this file is for...

2020-11-24 17:58 UTC, bobbyangers commented on arm-ttk/Test-AzTemplate.ps1
> +                    $isMainTemplate = 'mainTemplate.parameters.json', 'azureDeploy.parameters.json', 'prereq.azuredeploy.parameters.json' -contains $fileInfo.Name
@bmoore-msft  do we also modify it for the "azureDeploy.json" (line 319) ?   I was just following the set values for the other block.

2020-11-24 18:04 UTC, bobbyangers commented
> One thing we should pause on this is that the param file doesn't have to have this schema... it can be just the body of the parameters property or it can be the full schema. Both are valid for ARM to consume. I assume in that case we'd want to skip all the tests? or we need to modify how we identify the files and run the tests...
> 
> We should doc that case specifically.

Because of the way the files are selected; the validation would be skipped all together, so no harm done, no ?

Since ARM does consumes it anyway, then maybe; would be a good idea to issue a warning that if the file has the pattern ** 
 *.parameters.json** and no schema; then issue a warning; as it's good practice to put one.

2020-11-24 18:06 UTC, bobbyangers commented on arm-ttk/testcases/deploymentParameters/DeploymentParameters-ContentVersion-Must-Exist.test.ps1
> +if ($TemplateObject.contentVersion -notmatch '\d{1,3}\.\d{1,3}\.\d{1,5}\.\d{1,5}') {
[Understand the structure and syntax of ARM templates](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-syntax)
> Version of the template (such as 1.0.0.0). You can provide any value for this element. Use this value to document significant changes in your template. When deploying resources using the template, this value can be used to make sure that the right template is being used.

So using a numeric version, recommended, but not restricted;   should we just issue a warning then ?

2020-11-24 18:10 UTC, bobbyangers commented on arm-ttk/Test-AzTemplate.ps1
> +                                if ($key -eq 'DeploymentParameters' -and # Otherwise, if we're checking the deploymentTemplate
That is a good question.   I have seen some people use ***.parameters.dev.json**, ***.parameters.sbx.json** (sandbox) ;   so right now the way it was done for deploymentTemplate is to validate there was a **$schema** and go; that is my I chose to use the same technic.

As always; I am open to suggestions.

2020-11-24 18:11 UTC, bobbyangers commented on unit-tests/DeploymentParameters-Parameters-Property-Must-Exist/Fail/NotExist.parameters.should.be.ps1
> +﻿param(
I consulted the other tests, they use that file to validate the proper error message.  I tried to follow that pattern as well.  If you think just validating the error code; that is fine with me.

2020-11-24 18:13 UTC, bobbyangers commented on unit-tests/DeploymentParameters-Parameters-Property-Must-Exist/Pass/HasParameters.parameters.json
> +    "parameters": {}
done;

As for the reuse; you'll have to show me how (or point me to anther example).

2020-11-24 21:37 UTC, bobbyangers commented on unit-tests/DeploymentParameters-Parameters-Property-Must-Have-Value/Pass/HasValid.parameters.json
> +            "value" : "some data"
done.

2020-11-24 21:37 UTC, bobbyangers commented on arm-ttk/testcases/deploymentParameters/DeploymentParameters-Parameters-Property-Must-Have-Value.test.ps1
> +    Ensures that all parameters have a property 'value'
Great catch.... In fact I did use that option before.
I'll do that.
Actually added a little more....

2020-11-24 21:40 UTC, bobbyangers commented on unit-tests/DeploymentParameters-Schema-Is-Correct/Fail/BadSchema.parameters.should.be.ps1
> +﻿param(
removed

2020-11-25 20:03 UTC, bmoore-msft requested changes
There were one or two unresolved comments from the previous review...  other notes:

- to reuse a test file you can follow this pattern https://github.com/Azure/arm-ttk/blob/master/unit-tests/Location-Should-Not-Be-Hardcoded/Pass/MarketplaceSample.path.txt - basically a file with *.path.txt that contains a path to the file to use - thinking about it, your files are trivial enough it may not matter so I'll leave that up to you...

- the extraneous txt files in the unit-test folders should also be removed - I think that's related to the PS1 files.  I think those may have been missed in PR.  I'm going to file an issue to remind us...

2020-11-25 21:05 UTC, bobbyangers commented on arm-ttk/testcases/deploymentParameters/DeploymentParameters-Parameters-Property-Must-Have-Value.test.ps1
> +  if ( $p.Value.PsObject.Properties.match('value').Count){
Hi,   these are new tests that were added on top of checking just for "value", we now check for 'reference' as well, and make sure it is well formed.
Now this formula, is meant to check the presence for the 'value' in the properties collection.  I tried several options, and this is the one I found was working.
I tried => 'value' in $p.Value.PsObject.Properties.Name but could not get it to pass the tests.

2020-11-25 21:08 UTC, bobbyangers commented on unit-tests/arm-ttk.test.functions.ps1
> +                if (-not ($ttkResults | Where-Object {$_.Errors })) {
As I as was testing, and using the .txt files I was getting simply getting "expected errors"... I thought it be better to know which error it was expecting; So by checking it after looking at the txt file, then I could append the content and obtain a more complete error message.

It did however force me to repeat in the "else";   but I thought that the extra info was worth it.

2020-11-25 21:19 UTC, bobbyangers commented
> There were one or two unresolved comments from the previous review... other notes:
> 
> * to reuse a test file you can follow this pattern https://github.com/Azure/arm-ttk/blob/master/unit-tests/Location-Should-Not-Be-Hardcoded/Pass/MarketplaceSample.path.txt - basically a file with *.path.txt that contains a path to the file to use - thinking about it, your files are trivial enough it may not matter so I'll leave that up to you...

I'll look at that.

> * the extraneous txt files in the unit-test folders should also be removed - I think that's related to the PS1 files.  I think those may have been missed in PR.  I'm going to file an issue to remind us...

I thought the request was to remove the PS1 and keep the TXT.. did I get it wrong ? In any case, either is fine with me, but I think it's a good idea to test for the specific error.   I used other tests to discover that,
After some digging both can be used;  the TXT can be the ErrorId or some text to be searched in "any" of the error messages generated.
the PS1; is simply executed and expected to throw if the expected conditions are not met.

2020-11-25 21:24 UTC, bobbyangers commented on unit-tests/DeploymentParameters-ContentVersion-Must-Exist/Pass/2019-04-01.parameters.json
> +    "contentVersion": "1.0.0.0"
Sorry, I am not sure I follow...  
I modified the check where to check the version string and issue a warning;   the spec says we can put anything, but it's recommended to use "version" strings.

2020-11-26 13:18 UTC, closed without merging

2020-11-26 13:27 UTC, bobbyangers commented
Reshaped the commit (squashed them) to simplify