Added tests for DeploymentParameters
Azure/arm-ttk pull request #240
Opened 2020-11-26 13:49 UTC by bobbyangers

DeploymentParameters-Schema-Is-Correct.test
DeploymentParameters-ContentVersion-Must-Exist
DeploymentParameters-Parameters-Property-Must-Exist
DeploymentParameters-Parameters-Property-Must-Have-Value

For the full conversation:  please see [PR-237](https://github.com/Azure/arm-ttk/pull/237)

2020-12-03 16:48 UTC, bobbyangers commented
Hi @bmoore-msf, hope all is well in these crazy time!

Did you have a chance to look at this updated PR regarding Logic Apps?

2020-12-03 23:44 UTC, bobbyangers commented on arm-ttk/Test-AzTemplate.ps1
> +                    $templateFileName = $fileInfo.Name
Ok, I was just following the current method...

I am not sure how to go about doing what you asked.

2020-12-03 23:45 UTC, bobbyangers commented on unit-tests/DeploymentParameters-Parameters-Property-Must-Have-Value/Fail/BadSecretNameKeyVault.parameters.json
> +            "id" :"/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg1/providers/Microsoft.KeyVault/vaults/myvault"
In the regex, i used -imatch which already does a case insensitive match....

So what are you suggesting?

2020-12-03 23:46 UTC, bobbyangers commented on unit-tests/DeploymentParameters-Parameters-Property-Must-Have-Value/Pass/HasValid.parameters.json
> +        "value" : "[reference('other').output.value]"
Ok, I'll add a test for that in the fail section.

2020-12-08 19:05 UTC, bobbyangers commented
@bmoore-msft  any chance you'll be looking at this soon ?

2020-12-16 12:23 UTC, bobbyangers commented
Hi @bmoore-msft,
Any chance these get approuve soon?

2020-12-23 15:11 UTC, bobbyangers commented
Hi @bmoore-msft ,   I am not sure what do to next.  Can you please point me in the right direction ?

2020-12-29 00:20 UTC, bobbyangers reviewed
done

2021-01-14 18:54 UTC, bobbyangers commented
hi @bmoore-msft,  
Happy New Year.  Hope all is well.
how's it going ?   Still waiting for your input to close this....

2021-01-23 16:25 UTC, rangers-goodreason commented
Hi @bmoore-msft , I have taken some time to rebase this PR;  

please let me know if there is anything missing

2021-01-23 16:26 UTC, bobbyangers commented
Hi @bmoore-msft , I have taken some time to rebase this PR;

please let me know if there is anything missing

2021-02-16 16:05 UTC, bobbyangers commented
Hi @bmoore-msft  where do we stand on this ?

2021-02-16 16:33 UTC, bobbyangers commented on unit-tests/DeploymentParameters-Parameters-Property-Must-Have-Value/Fail/BadSecretNameKeyVault.parameters.json
> +          "secretName": "some_invalid_value"
no longer applicable

2021-02-16 16:33 UTC, bobbyangers commented on unit-tests/DeploymentParameters-Parameters-Property-Must-Have-Value/Pass/HasValid.parameters.json
> +        "value" : "[reference('other').output.value]"
no longer applicable

2021-02-18 21:32 UTC, bmoore-msft requested changes
Sorry for the delay bobby, finally getting back to some of these...

I do like the stuff you're adding...

2021-02-18 21:32 UTC, bmoore-msft commented on arm-ttk/Test-AzTemplate.ps1
> +                    $templateFileName = $fileInfo.Name
Ok, sorry for the delay here...  I think we want to have a new set of "global" vars for the param file equivalent, e.g.
```
$parameterFileName
$parameterObject
$parameterText
```
Rather than overloading the $template* variables.  Right now I can't think of a problem it will cause, but if we do find one later, cleaning up will be much harder.  So better to separate them from the start.

2021-02-18 21:32 UTC, bmoore-msft commented on arm-ttk/Test-AzTemplate.ps1
> +                    $isMainTemplate = 'maintemplate.parameters.json', 'azuredeploy.parameters.json', 'prereq.azuredeploy.parameters.json' -contains $fileInfo.Name
change this to $isMainTemplateParameters

2021-02-18 21:32 UTC, bmoore-msft commented on arm-ttk/Test-AzTemplate.ps1
> +                                'maintemplate.parameters.json', 'azuredeploy.parameters.json', 'prereq.azuredeploy.parameters.json' -contains $fn) { # and the file name is something we _know_ will be
should this just be: *.parameters.json ?

Also what happens if I don't name my param file with this pattern (or have no param file) - are the tests simply not executed?  I think so, but want to confirm.

2021-02-18 21:32 UTC, bmoore-msft commented on arm-ttk/testcases/deploymentParameters/DeploymentParameters-Parameters-Property-Must-Have-Value.test.ps1
> +  $TemplateObject
this would need to change with the changes above, i.e. $parameterObject

2021-02-18 21:32 UTC, bmoore-msft commented on arm-ttk/testcases/deploymentParameters/DeploymentParameters-Parameters-Property-Must-Have-Value.test.ps1
> +  if ( -not ($p.Value.PsObject.Properties.match('value').Count -or $p.Value.PsObject.Properties.match('reference').Count )) {
I think this can be simplified, e.g. first check to see if the required properties are present, must have 1 of the following:
```powershell
if($p.Value.PSObject.properties["value"] -or $p.Value.PSObject.properties["reference"]){
    continue
}
```

Then I think you can skip to [the current] line 36

2021-02-18 21:32 UTC, bmoore-msft commented on arm-ttk/testcases/deploymentParameters/DeploymentParameters-Parameters-Property-Must-Have-Value.test.ps1
> +      # Keyvalut naming restrictions, ref: https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules#microsoftkeyvault
typo

2021-02-18 21:32 UTC, bmoore-msft commented on arm-ttk/testcases/deploymentParameters/DeploymentParameters-Parameters-Property-Must-Have-Value.test.ps1
> +        Write-Error -ErrorId Parameters.Parameter.Bad.KeyVault.Id -TargetObject $p.Value.reference.keyVault.id -Message "'$($p.Name)'.reference.keyValut.id contains improper value, `r`n Should be lik
typo in keyVault

2021-02-18 21:32 UTC, bmoore-msft commented on unit-tests/DeploymentParameters-Parameters-Property-Must-Have-Value/Fail/BadSecretNameKeyVault.parameters.json
> +            "id" :"/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg1/providers/Microsoft.KeyVault/vaults/myvault"
just having a test case that's checking that your -inotmatch doesn't change to -cnotmatch...

2021-02-18 21:32 UTC, bmoore-msft commented on unit-tests/DeploymentParameters-Parameters-Property-Must-Have-Value/Pass/HasValid.parameters.json
> +            "id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg1/providers/Microsoft.KeyVault/vaults/myvault"
add some alpha chars to the guid since your regex checks them

2021-02-18 22:55 UTC, bobbyangers commented on arm-ttk/testcases/deploymentParameters/DeploymentParameters-Parameters-Property-Must-Have-Value.test.ps1
> +  if ( -not ($p.Value.PsObject.Properties.match('value').Count -or $p.Value.PsObject.Properties.match('reference').Count )) {
Hi @bmoore-msft ,

I am not sure about your claim.    the current code, splits the errors into more specific errors, 
1.  making sure either 'value' or 'reference'
2.  if value => cannot be a reference [somefunction()]
3.  if reference => checks the validity

as per my comment, not checking for Count can result in false positive when property contains a 'falsy' value.

It is important to allow, 0, false;   

I don't see how your proposal would cover those cases

2021-02-18 22:57 UTC, bobbyangers commented on arm-ttk/Test-AzTemplate.ps1
> +                                'maintemplate.parameters.json', 'azuredeploy.parameters.json', 'prereq.azuredeploy.parameters.json' -contains $fn) { # and the file name is something we _know_ will be
Yes, as before, it did not check files it did that do not follow the pattern.

2021-02-19 02:40 UTC, bobbyangers commented on arm-ttk/testcases/deploymentParameters/DeploymentParameters-Parameters-Property-Must-Have-Value.test.ps1
> +  $TemplateObject
if we change this, then we would need to also change how this file gets called, the parameter is passed by name.

2021-02-25 22:13 UTC, bmoore-msft commented on arm-ttk/Test-AzTemplate.ps1
> +                                'maintemplate.parameters.json', 'azuredeploy.parameters.json', 'prereq.azuredeploy.parameters.json' -contains $fn) { # and the file name is something we _know_ will be
For template files we check all json files and then have additional tests for the "main" templates...  seems like should follow that pattern here too, otherwise folks will expect thing are checked and they won't be...

2021-02-25 22:16 UTC, bmoore-msft commented on arm-ttk/testcases/deploymentParameters/DeploymentParameters-Parameters-Property-Must-Have-Value.test.ps1
> +  $TemplateObject
yes - we will...

As a side note, coming back to this PR I was still lost thinking we were looping on the template (not the params) so I definitely think we need to separate them...

2021-02-25 22:30 UTC, bmoore-msft requested changes

2021-02-25 22:30 UTC, bmoore-msft commented on arm-ttk/testcases/deploymentParameters/DeploymentParameters-Parameters-Property-Must-Have-Value.test.ps1
> +foreach ($p in $TemplateObject.parameters.psobject.properties) {
it's possible that the param file does not have a param object - a valid param file might just contain the name value pairs, e.g.

```json
{
  "adminUsername": {
    "value": "someuser"
  }
}
```

So we need to account for that case.

2021-02-25 22:30 UTC, bmoore-msft commented on arm-ttk/testcases/deploymentParameters/DeploymentParameters-Parameters-Property-Must-Have-Value.test.ps1
> +  if ( -not ($p.Value.PsObject.Properties.match('value').Count -or $p.Value.PsObject.Properties.match('reference').Count )) {
The proposed would will tell you existence of the property, which I think is what's needed here.  If the property contains $null, 0, false, empty string - those are valid values for an arm template parameter.  So pass the existence and "is my value valid" test.

I think the part that jumping out is that the proposed sytnax is more readable than the ".match().count"

2021-03-01 04:45 UTC, bobbyangers commented on arm-ttk/Test-AzTemplate.ps1
> +                                'maintemplate.parameters.json', 'azuredeploy.parameters.json', 'prereq.azuredeploy.parameters.json' -contains $fn) { # and the file name is something we _know_ will be
With James' help; we fixed this.

2021-03-01 04:45 UTC, bobbyangers commented on arm-ttk/testcases/deploymentParameters/DeploymentParameters-Parameters-Property-Must-Have-Value.test.ps1
> +  $TemplateObject
With James' help; done.

2021-03-01 04:50 UTC, bobbyangers commented on arm-ttk/testcases/deploymentParameters/DeploymentParameters-Parameters-Property-Must-Have-Value.test.ps1
> +foreach ($p in $TemplateObject.parameters.psobject.properties) {
Is this an undocumented feature ?
According to this page;  
[Create Resource Manager parameter file](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/parameter-files)

That does not seem to be an option.

Would it not be a case where a user might decide to not check a rule ?

2021-03-01 23:53 UTC, bmoore-msft commented on arm-ttk/testcases/deploymentParameters/DeploymentParameters-Parameters-Property-Must-Have-Value.test.ps1
> +  if ( -not ($p.Value.PsObject.Properties.match('value').Count -or $p.Value.PsObject.Properties.match('reference').Count )) {
I don't see what you changed here?

2021-03-02 00:04 UTC, bobbyangers commented on arm-ttk/testcases/deploymentParameters/DeploymentParameters-Parameters-Property-Must-Have-Value.test.ps1
> +  if ( -not ($p.Value.PsObject.Properties.match('value').Count -or $p.Value.PsObject.Properties.match('reference').Count )) {
I will change it as you ask.

but what I understand from Powershell is that
if($p.Value.PSObject.properties["value"]) ==> false if the propertie is missing or 
contains a "falsy" value: 0, $null, false, empty string, empty array; 

if that is the case, then if the property exists, but contains a "falsy" value, then your suggestion will yield a false positive result.

2021-03-05 21:57 UTC, bmoore-msft commented on arm-ttk/testcases/deploymentParameters/DeploymentParameters-Parameters-Property-Must-Have-Value.test.ps1
> +foreach ($p in $TemplateObject.parameters.psobject.properties) {
It probably is undocumented but valid so we need to figure out the difference and which tests to run...

2021-03-06 00:01 UTC, bobbyangers commented on arm-ttk/testcases/deploymentParameters/DeploymentParameters-Parameters-Property-Must-Have-Value.test.ps1
> +foreach ($p in $TemplateObject.parameters.psobject.properties) {
Hi @bmoore-msft, at the moment the are not being tested; so if the developer wanted to be tested, why not simply expect them to follow the documented features.

I understand what you want, however, pushing this update will enhance the product, and ignore some undocumented features; which by the way, is what it's doing now.

My vote is to push it as is; and enhance it later.

2021-03-08 17:54 UTC, bmoore-msft commented on arm-ttk/testcases/deploymentParameters/DeploymentParameters-Parameters-Property-Must-Have-Value.test.ps1
> +foreach ($p in $TemplateObject.parameters.psobject.properties) {
The main scenario is for generating params - a simple hashtable is easier to generate than ones with the extra properties/schema.  Though to be fair, those aren't often checked into source, so it just depends on when the ttk is executed.

If we push and find out we're breaking folks, we'd have to roll back.

@StartAutomating - any objections?

2021-03-08 18:30 UTC, bobbyangers commented on arm-ttk/testcases/deploymentParameters/DeploymentParameters-Parameters-Property-Must-Have-Value.test.ps1
> +foreach ($p in $TemplateObject.parameters.psobject.properties) {
That, or we could remove that particular test.

2021-03-08 19:00 UTC, bobbyangers commented
Hi @bmoore-msft ,

I have attempted to rebase, but it seems the tests are failing on this:
>> Resources-Should-Not-Be-Ambiguous.test
It looks like you just put an "exit" at the top of the file, so now the "should fail" are blocking this commit.

Describing Resources-Should-Not-Be-Ambiguous

  Context Fail
    [-] Validates ResourceTypeFirstParameter is flagged 21ms
      RuntimeException: Errors were expected
      at <ScriptBlock>, C:\Users\Robert\source\repos\arm-ttk\unit-tests\arm-ttk.test.functions.ps1: line 125
    [-] Validates trailing-slash is flagged 29ms
      RuntimeException: Errors were expected
      at <ScriptBlock>, C:\Users\Robert\source\repos\arm-ttk\unit-tests\arm-ttk.test.functions.ps1: line 125

  Context Pass
    [+] Validates NestedResourceType is correct 17ms
    [+] Validates SimpleResourceID is correct 18ms
    [+] Validates top-level-child-expression is correct 23ms
    [+] Validates topLevelChild is correct 19ms

2021-03-11 21:34 UTC, bmoore-msft commented
yep - moved those if you want to try again

2021-03-11 21:55 UTC, bmoore-msft commented on arm-ttk/Test-AzTemplate.ps1
> +                                if ($key -eq 'DeploymentParameters' -and # Otherwise, if we're checking the deploymentTemplate
this seems like it's going to filter out tests, esp the schema test...  can we confirm the following.

- if the file is named like *.parameters.json AND
- the file has a property named "$schema"

run all of the parameter file tests.

The code here seems to filter on the schema property value which will mean that we skip schema test itself.

2021-03-11 22:51 UTC, rangers-goodreason commented on arm-ttk/Test-AzTemplate.ps1
> +                                if ($key -eq 'DeploymentParameters' -and # Otherwise, if we're checking the deploymentTemplate
Hi @bmoore-msft ,

> [290] foreach ($key in $TestGroup.Keys) { # If it didn't have a schema

I am not sure why you are asking to check for the schema ?

Plus I think this is getting checked at line 318

> [318]  if ($fileInfo.Schema -like '*deploymentParameters*')

2021-03-12 18:41 UTC, bmoore-msft commented on arm-ttk/Test-AzTemplate.ps1
> +                                if ($key -eq 'DeploymentParameters' -and # Otherwise, if we're checking the deploymentTemplate
parameter files have 2 [valid] schemas.  TLDR; one includes a $schema, contentVersion, and parameters property.  The other is a simple object with the contents of what would be in the parameters property in the first schema.

If we find a file named ```azuredeploy.parameters.json``` but it doesn't have a schema property, we should assume it won't have a parameters property either - and then skip the tests or adjust accordingly.  Adjusting is the right answer, but I think we can defer that to another PR.

This check:
```
if ($fileInfo.Schema -like 'deploymentParameters')
```

should be seconday, otherwise we will fail to test files named ```*.parameters.json``` but have the deploymentTemplate schema.

Essentially what this means, is that we will assert some file is a param file by only the filename (which I think is fine in this case).  Then we can test for more/all issues in the $schema property.

2021-03-12 19:20 UTC, bobbyangers commented
Hi Brian.

I am sorry, maybe we can organise a quick call with you or James?  I thought we would not support the scenario you are proposing;

--Robert Angers
m:514-557-8074

Sent from my iPhone

On Mar 12, 2021, at 13:48, Brian Moore ***@***.***> wrote:

﻿

@bmoore-msft commented on this pull request.

________________________________

In arm-ttk/Test-AzTemplate.ps1<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Farm-ttk%2Fpull%2F240%23discussion_r593374925&data=04%7C01%7C%7Cca9037337c054de62ed108d8e58762a5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637511716917236711%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2nnMXfUxkCw90Z8G3OSBV6Uz31DnlapMzYAOg1xPrJU%3D&reserved=0>:

> @@ -293,9 +293,12 @@ Each test script has access to a set of well-known variables:
                                 if ($fn -match $key) { # check to see if it's name matches the key
                                     $key; continue # (this handles CreateUIDefinition.json, even if no schema is present).
                                 }
+                                if ($key -eq 'DeploymentParameters' -and # Otherwise, if we're checking the deploymentTemplate


parameter files have 2 [valid] schemas. TLDR; one includes a $schema, contentVersion, and parameters property. The other is a simple object with the contents of what would be in the parameters property in the first schema.

If we find a file named azuredeploy.parameters.json but it doesn't have a schema property, we should assume it won't have a parameters property either - and then skip the tests or adjust accordingly. Adjusting is the right answer, but I think we can defer that to another PR.

This check:

if ($fileInfo.Schema -like 'deploymentParameters')


should be seconday, otherwise we will fail to test files named *.parameters.json but have the deploymentTemplate schema.

Essentially what this means, is that we will assert some file is a param file by only the filename (which I think is fine in this case). Then we can test for more/all issues in the $schema property.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Farm-ttk%2Fpull%2F240%23discussion_r593374925&data=04%7C01%7C%7Cca9037337c054de62ed108d8e58762a5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637511716917246706%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2F05DkaI%2FytiV4Sxpk8dB7UDMWLYz8SUjKOxFHHVhYU0%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAANL524Z3D3U7CTLYLFXVGDTDJHVVANCNFSM4UDYHUKA&data=04%7C01%7C%7Cca9037337c054de62ed108d8e58762a5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637511716917246706%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=AoDecRgl2m9X88ymaooQo8eWmfsWGxiaZb31afoIeEA%3D&reserved=0>.

2021-03-16 23:13 UTC, bobbyangers reviewed
I 'll wait for further instructions.

2021-05-23 00:33 UTC, bobbyangers commented on arm-ttk/Test-AzTemplate.ps1
> +                                if ($key -eq 'DeploymentParameters' -and # Otherwise, if we're checking the deploymentTemplate
@bmoore-msft, @StartAutomating and myself reviewed the various points mentioned in the last commit,
1.   allowed ***.parameters.json** to be picked up
2. added guard clauses to account for $schemaless parameter files
3. renamed the tests files to better reflect intent

2021-05-23 02:26 UTC, bobbyangers commented
@bmoore-msft   Please latest updates done in concurence with @StartAutomating ;   to comply with your request regarding the **schemaless** scenario.

2021-05-27 23:38 UTC, bmoore-msft commented
Yea!

2021-05-27 23:38 UTC, merged