module integrity testing
Azure/arm-ttk pull request #241
Opened 2020-11-26 19:42 UTC by bobbyangers

Added tests to do basic testing of module integrity.

- Test module manifest file exists **arm-ttk.psm1**
- Test module main file exists **arm-ttk.psd1** and refers **arm-ttk.psm1**
- Test file exists: **Test-AzTemplate.ps1**, **Test-AzTemplate.cmd**, **Test-AzTemplate.sh**
- Loops through all **.\arm-ttk\testcases\*.ps1** files
    - validates is valid **PowerShell** script
    - validates has comment/documentation block
      - block contains a **SYNOPSIS**
      - block contains a **DESCRIPTION**
      - [block contains **EXAMPLE**] skipped for now
      
I have also added some "stubs" for the dozen of so file missing the comment block sections

2020-12-03 16:47 UTC, bobbyangers commented
Hi @bmoore-msft,

Hope is well.

any chance you can approve my PR?

2020-12-03 22:24 UTC, bmoore-msft requested changes

2020-12-03 22:24 UTC, bmoore-msft commented on arm-ttk/testcases/CreateUIDefinition/CreateUIDefinition-Should-Have-Schema.test.ps1
> +    TODO: summary of test
I'd rather not have TODO's here otherwise we're getting a false sense of "these are complete"...  Can you add proper text for these, you can steal it from here: https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/test-cases

I think the experience of getting a TODO when I request help, is worse than nothing TBH

2020-12-03 22:24 UTC, bmoore-msft commented on unit-tests/arm-ttk.module.tests.ps1
> +﻿<#
can you put this into a folder, named such that it will run before all the other tests... e.g.

_arm-ttk-module

2020-12-03 22:28 UTC, bobbyangers commented on arm-ttk/testcases/CreateUIDefinition/CreateUIDefinition-Should-Have-Schema.test.ps1
> +    TODO: summary of test
Yes of course; i just did not want to "improvise" a proper description.

There are about 10 of them to fix.

2020-12-03 22:30 UTC, bobbyangers commented on unit-tests/arm-ttk.module.tests.ps1
> +﻿<#
I am not sure what you mean that it will "run before all"...
I'll try it out shorthly.

2020-12-04 01:41 UTC, bobbyangers commented
I have rebased the my branch to facilitate the merge/PR.

2020-12-04 01:44 UTC, bobbyangers commented
@bmoore-msft  >> I have rebased my branch to facilitate the merge/PR

2020-12-08 19:05 UTC, bobbyangers commented
@bmoore-msft  any chance you'll be looking at this soon ?

2020-12-16 12:24 UTC, bobbyangers commented
Hi @bmoore-msft ,

Any chance these get approuve soon?

2020-12-21 23:34 UTC, bobbyangers commented
Hi @bmoore-msft;  how are you ?  I hope all is well.    

Can we take a look at this and PR these changes ?

2020-12-23 15:12 UTC, bobbyangers commented
Hi @bmoore-msft , I am not sure what do to next. Can you please point me in the right direction ?

2020-12-29 00:18 UTC, bobbyangers reviewed
Done

2021-01-23 16:17 UTC, rangers-goodreason commented
Hi @bmoore-msft  , I have taken the time to rebase this PR.  
Can you re-check it and comment ?

2021-01-23 16:28 UTC, bobbyangers commented
Hi @bmoore-msft , I have taken the time to rebase this PR.
Can you re-check it and comment ?

2021-02-16 16:05 UTC, bobbyangers commented
Hi @bmoore-msft where do we stand on this ?

2021-02-18 21:37 UTC, merged