Check resource section only to avoid “call depth overflow errors”
Azure/arm-ttk pull request #265
Opened 2020-12-17 09:26 UTC by tiefpunkt

We've been observing "The script failed due to call depth overflow." errors on the following three checks:
* adminUsername Should Not Be A Literal
* IDs Should Be Derived From ResourceIDs
* VM Size Should Be A Parameter
 
The errors occurred both in the hosted checks for the Azure marketplace as well as when running them locally:
![image](https://user-images.githubusercontent.com/434444/102468441-cd8c8880-4051-11eb-8c37-025eba1ecee2.png)
![image](https://user-images.githubusercontent.com/434444/102468554-f3199200-4051-11eb-90b1-aa6a5943e6ea.png)

I was not able to track down the exact source of the error, but noticed that most other checks focus on a specific section of the template instead of the entire template. That seems to make sense for these three checks as well, so I adjusted them accordingly. Now they go through without any issues and in much less time:
![image](https://user-images.githubusercontent.com/434444/102468738-370c9700-4052-11eb-868b-feea8aa212e2.png)

Sorry for the whitespace changes, they were done by my text editor automatically.

2021-01-08 20:34 UTC, bmoore-msft requested changes
See comments - I think we can take pieces of the PR to unblock this (it is a PITA) - we'd also like to resolve the root cause.

Do you have a template/sample that we can use to repro the overflow and debug the underlying cause?  (can file an issue and attach if so)

2021-01-08 20:34 UTC, bmoore-msft commented on arm-ttk/testcases/deploymentTemplate/IDs-Should-Be-Derived-From-ResourceIDs.test.ps1
> +$ids = $TemplateObject.resources | Find-JsonContent -Key *id -Like
can you make sure we have a unit test that will grab a resourceId property from a variable?

2021-01-08 20:34 UTC, bmoore-msft commented on arm-ttk/testcases/deploymentTemplate/adminUsername-Should-Not-Be-A-Literal.test.ps1
> +$adminUserNameRefs = $TemplateObject.resources |
this won't work here because I could have a variable with the same name and while that's not a 100% accurate test, it is something we want to test...

2021-01-09 23:00 UTC, tiefpunkt commented on arm-ttk/testcases/deploymentTemplate/IDs-Should-Be-Derived-From-ResourceIDs.test.ps1
> +$ids = $TemplateObject.resources | Find-JsonContent -Key *id -Like
The `pass3` resource in `arm-ttk/unit-tests/IDs-Should-Be-Derived-From-ResourceIDs/Pass/exceptions-that-should-pass.json` does that, I think.

2021-01-09 23:30 UTC, tiefpunkt commented on arm-ttk/testcases/deploymentTemplate/adminUsername-Should-Not-Be-A-Literal.test.ps1
> +$adminUserNameRefs = $TemplateObject.resources |
Is it better now?

2021-01-09 23:31 UTC, tiefpunkt commented
I do have a template where this currently fails, but it's a marketplace solution template, which I'm not sure I'm allowed to attach here, sorry.

2021-01-21 22:26 UTC, bmoore-msft commented
@tiefpunkt - changes look good, would still like to get the repro template - if the marketplace offer is live, then the template code is public... but if you want, just tell me which offer is it and I can go pull it.

2021-01-21 22:26 UTC, merged

2021-01-23 09:05 UTC, tiefpunkt commented
@bmoore-msft It went live this week: https://azuremarketplace.microsoft.com/en-us/marketplace/apps/lnw-softgmbh.phoenix-s4hana