Publish to PowerShell Gallery
Azure/arm-ttk pull request #268
Opened 2020-12-22 16:14 UTC by MarcusFelling

To get started on #182 I would like to get arm-ttk published to the PowerShell gallery for more streamlined consumption. 

We will need to identify an [MSA account](https://osgwiki.com//wiki/Internal_Guidelines_for_Adding_to_the_Powershell_Gallery) then generate an API key and add it as a secret in this repo as "NuGetAPIKey".

2020-12-22 16:17 UTC, MarcusFelling commented
@bmoore-msft - Do you have access to an MSA account for this?

2021-01-08 21:17 UTC, bmoore-msft requested changes

2021-01-08 21:17 UTC, bmoore-msft commented on arm-ttk/arm-ttk.psd1
> +    ModuleVersion = '0.3.#{Patch}#'
I think this will cause the local import-module... so I think what we'll do is only publish when this file is changed in a PR... so it has to be intentional, and local import will still work fine.  Keeping in mind that all pipelines today are using this local import approach.  (so this would instantly break those)

2021-01-08 21:17 UTC, bmoore-msft commented on .github/workflows/test-publish.yml
> +          (Get-Content "$env:GITHUB_WORKSPACE\$env:ModulePath") -replace '#{Patch}#', "$env:GITHUB_RUN_NUMBER" `
Let's make this an explicit choice or intentional step - rather than pushing every PR to the gallery... this will keep the noise/versions down the the ecosystem isn't as fragmented and also reduce the risk that we instantly break everyone until we mature a bit ;)

2021-01-08 21:17 UTC, bmoore-msft commented on .github/workflows/test-publish.yml
> +          Publish-Module -Path "$env:GITHUB_WORKSPACE/$env:ModuleFolder" -NuGetAPIKey $env:NuGetAPIKey
Here we need an explicit check against the gallery version - if they are the same, don't publish...

2021-01-08 21:17 UTC, bmoore-msft commented on arm-ttk/arm-ttk.psd1
> +    Author = 'azure-sdk'
let's use 'arm-ttk' for the author, the sdk folks are different ;)

2021-01-08 21:17 UTC, bmoore-msft commented on arm-ttk/arm-ttk.psd1
> +    Copyright = 'Microsoft Corporation. All rights reserved.'
need to add a year, e.g. 2021

2021-01-08 21:18 UTC, bmoore-msft commented
Thanks - I need to go hunt down the key and an MSA...

2021-01-11 20:24 UTC, MarcusFelling commented on arm-ttk/arm-ttk.psd1
> +    Author = 'azure-sdk'
I wasn't sure if we would have to share with sdk or not. arm-ttk it is! :-)

2021-01-11 20:24 UTC, MarcusFelling commented on .github/workflows/test-publish.yml
> +          Publish-Module -Path "$env:GITHUB_WORKSPACE/$env:ModuleFolder" -NuGetAPIKey $env:NuGetAPIKey
I assume we will still want to limit this to master branch only?

2021-01-11 20:24 UTC, MarcusFelling commented on .github/workflows/test-publish.yml
> +          (Get-Content "$env:GITHUB_WORKSPACE\$env:ModulePath") -replace '#{Patch}#', "$env:GITHUB_RUN_NUMBER" `
As mentioned above, versioning will be handled through manifest file updates for now. I have removed this step from the workflow.

2021-01-11 20:25 UTC, MarcusFelling commented on arm-ttk/arm-ttk.psd1
> +    ModuleVersion = '0.3.#{Patch}#'
Ok, i will remove the token place holder. I had the token replacement setup early in the pipeline process to get them to work.  However, you're correct this could hinder local dev, unless a separate dev/local manifest is used. I wasn't sure if you wanted the publish process to be more "automated" or not.  I think manually updating the manifest's version will give us a simple approach to start.

2021-01-21 22:50 UTC, bmoore-msft requested changes

2021-01-21 22:50 UTC, bmoore-msft commented on .github/workflows/test-publish.yml
> +name: test-publish
Let's separate this from the CI/CD pipeline and set this up with a workflow dispatch trigger - that will ensure that publishing is a conscious step and give us time to dogfood a pr if we feel the need. (and not have to reject a PR if we're cautious).

2021-01-27 15:35 UTC, MarcusFelling commented
Given other priorities, I'm going to close out this PR

2021-01-27 15:35 UTC, closed without merging