When testing for presence of length constraint, test at beginning of regex as well.
Azure/arm-ttk pull request #284
Opened 2021-01-21 23:17 UTC by edburns

modified:   arm-ttk/testcases/CreateUIDefinition/Textboxes-Are-Well-Formed.test.ps1

- When testing for presence of length constraint, test at beginning of regex as well.

2021-01-29 19:49 UTC, bmoore-msft requested changes
Can you add unit test for the new cases you want to cover with this?

2021-02-18 21:38 UTC, bmoore-msft commented
@edburns are you able to add some unit tests for this?

2021-02-24 07:32 UTC, zhengchang907 commented
@edburns Can you please review the unit test I added and resolve the change requests?

2021-02-25 17:51 UTC, edburns commented
@zhengchang907 I approve the unit test, but I don't know how to accept the change request. The **approve** button is grayed out for me.  @bmoore-msft  can you approve it?

2021-02-26 01:26 UTC, zhengchang907 commented on unit-tests/Textboxes-Are-Well-Formed/Pass/Textboxes-Without-Length-Constrains-Regex/createUiDefinition.json
> +{
Hi Brian, here we only throw out warnings instead of errors. The reason for doing so is that usually the value users type in here will be passed directly to downstream as a parameter, and there is another constrain there really matters and the constrain varies from case to case.

2021-02-26 01:39 UTC, edburns commented on unit-tests/Textboxes-Are-Well-Formed/Pass/Textboxes-Without-Length-Constrains-Regex/createUiDefinition.json
> +{
@zhengchang907 I expect @bmoore-msft was asking for a comment in the json file. Note that [comments are supported in JSON](https://github.com/Azure/azure-resource-manager-schemas/issues/851) for ARM and `createUiDefinition`.

2021-02-26 01:45 UTC, zhengchang907 commented on unit-tests/Textboxes-Are-Well-Formed/Pass/Textboxes-Without-Length-Constrains-Regex/createUiDefinition.json
> +{
Oh sorry I misunderstood, will add comments today

2021-02-26 01:47 UTC, edburns commented on unit-tests/Textboxes-Are-Well-Formed/Pass/Textboxes-Without-Length-Constrains-Regex/createUiDefinition.json
> +{
No problem. We have generated clarity.

2021-02-26 05:07 UTC, zhengchang907 commented on unit-tests/Textboxes-Are-Well-Formed/Pass/Textboxes-Without-Length-Constrains-Regex/createUiDefinition.json
> +{
@bmoore-msft @edburns Hi fellas, I've added comments to explain the reason

2021-02-26 20:53 UTC, bmoore-msft commented on unit-tests/Textboxes-Are-Well-Formed/Pass/Textboxes-Without-Length-Constrains-Regex/createUiDefinition.json
> +{
thanks

2021-02-26 20:54 UTC, merged