Add inner template test case for APIVersion-Should-Be-Recent
Azure/arm-ttk pull request #540
Opened 2021-11-08 05:41 UTC by galiacheng

Calling an API in the inner template, test case `apiVersions-Should-Be-Recent` constructs the resource type by adding prefix "Microsoft.Resources/deployments", then getting resource type like "Microsoft.Resources/deployments/Microsoft.Network/dnsZones", which causes the test fail. This case should pass.

2021-11-11 16:56 UTC, bmoore-msft requested changes

2021-11-11 16:56 UTC, bmoore-msft commented on arm-ttk/testcases/deploymentTemplate/apiVersions-Should-Be-Recent.test.ps1
> +                $parent=$av.ParentObject[$i]
format the code, e.g. SHIFT+ALT+F in VS Code

2021-11-11 16:56 UTC, bmoore-msft commented on arm-ttk/testcases/deploymentTemplate/apiVersions-Should-Be-Recent.test.ps1
> +                $expEvaOptions= $parent.properties.expressionEvaluationOptions
Should probably name the var ```expEvalOptions``` (add an L)

2021-11-11 16:56 UTC, bmoore-msft commented on arm-ttk/testcases/deploymentTemplate/apiVersions-Should-Be-Recent.test.ps1
> +
remove whitespace

2021-11-11 16:56 UTC, bmoore-msft commented on unit-tests/apiversions-should-be-recent/Pass/Api-In-Inner-Template.json
> +{
Let's add a fail test case as well

2021-11-11 16:56 UTC, bmoore-msft commented on arm-ttk/testcases/deploymentTemplate/apiVersions-Should-Be-Recent.test.ps1
> +                        continue
Not sure I follow here though - we don't want to skip the test, we just don't want to add the parent of ```Microsoft.Resources/deployment``` right?

2021-11-11 16:56 UTC, bmoore-msft commented on arm-ttk/cache/AllAzureResources.cache.json
> +        "2021-04-01",
this file is autogenerated so these changes will be overwritten - so let's just remove them.

2021-11-12 09:53 UTC, galiacheng commented on arm-ttk/testcases/deploymentTemplate/apiVersions-Should-Be-Recent.test.ps1
> +                        continue
Yes, I will enhance the comment

2021-11-12 10:05 UTC, galiacheng commented on arm-ttk/testcases/deploymentTemplate/apiVersions-Should-Be-Recent.test.ps1
> +                $parent=$av.ParentObject[$i]
Fixed in https://github.com/Azure/arm-ttk/pull/540/commits/fb722d374d7c6942ede76ffc0a088a83ad8e8691

2021-11-12 10:05 UTC, galiacheng commented on arm-ttk/testcases/deploymentTemplate/apiVersions-Should-Be-Recent.test.ps1
> +                $expEvaOptions= $parent.properties.expressionEvaluationOptions
Fixed in https://github.com/Azure/arm-ttk/pull/540/commits/fb722d374d7c6942ede76ffc0a088a83ad8e8691

2021-11-12 10:05 UTC, galiacheng commented on arm-ttk/testcases/deploymentTemplate/apiVersions-Should-Be-Recent.test.ps1
> +
Fixed in https://github.com/Azure/arm-ttk/pull/540/commits/fb722d374d7c6942ede76ffc0a088a83ad8e8691

2021-11-12 10:06 UTC, galiacheng commented on unit-tests/apiversions-should-be-recent/Pass/Api-In-Inner-Template.json
> +{
Fix in https://github.com/Azure/arm-ttk/pull/540/commits/fb722d374d7c6942ede76ffc0a088a83ad8e8691

2021-11-12 10:06 UTC, galiacheng commented on arm-ttk/testcases/deploymentTemplate/apiVersions-Should-Be-Recent.test.ps1
> +                        continue
Fixed in https://github.com/Azure/arm-ttk/pull/540/commits/fb722d374d7c6942ede76ffc0a088a83ad8e8691

2021-11-12 10:06 UTC, galiacheng commented on arm-ttk/cache/AllAzureResources.cache.json
> +        "2021-04-01",
Done

2021-11-12 21:31 UTC, merged